### ISSUE TITLE
Citation Scheme

### ISSUE THREAD

**Issue by BakerBelays** [observational-dev/oawiki#10]
We need a useful scheme to create citations, be it for images or pieces of information. This should be a priority- it separates the wiki from other sources that often self-cite or rely on things they've heard (CN, Discord, etc)

**Comment by peytondmurray** [comment]
There's a couple of options here:

1. Use [footnotes](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#footnotes) as a simpler way of doing this
2. If we want something more formal, we can use [sphinxcontrib-bibtex](https://sphinxcontrib-bibtex.readthedocs.io/en/latest/index.html) which can actually render citations specified in a `refs.bib` file:
![image](https://github.com/observational-dev/oawiki/assets/14017872/bf72e0a3-cc1c-4ae6-a002-af9a34b4fed5)

The problem with option 2 is (quoting the docs)

> Citations in sphinx are resolved globally across all documents. Typically, you have a single bibliography directive across your entire project which collects all citations. Advanced use cases with multiple bibliography directives across your project are also supported, but some care needs to be taken from your end to avoid duplicate citations.

**Comment by BakerBelays** [comment]
Yep, then footnotes makes the most sense. Most of the time the citations are just going to be leading people to good places. Glad to see Sphinx is strong.

Certain resources will be getting pulled from often, especially physical text when it comes to ATM. It might make sense to have a small bibliography library in addition to the footnotes, but that's probably best addressed when we get to that point

**Comment by random-person-001** [comment]
+1 for footnotes for now, and after we have a fair amount of content, if we feel like a bibliography would be useful, we cross that road when we get there
