### ISSUE TITLE
Better distinguishability of h1/h2/h3/h4

### ISSUE THREAD

**Issue by peytondmurray** [observational-dev/oawiki#18]
**Describe the solution you'd like**
Headings are not distinguishable enough. Modify the variables that control heading font size and weight to make them more visible. `--pst-font-size-h1`

**Additional context**
See https://wiki.observational.space/planetary_imaging.html for an example. Note that subheadings are correctly nested on the right hand sidebar but are nearly impossible to tell apart in the content itself.

**Comment by BakerBelays** [comment]
Font style is also a question- h1/h2 headers should probably be serif fonts

**Comment by the-guruji** [comment]
Andy is making a mock-up for this in Figma (including fonts/colours and other layout options).

Based on that, and on constraints with CSS I suppose, we can make a full style guide for authors/editors to conform to (simple things like don't use more than two or three levels of headings, and so on).
