### ISSUE TITLE
Contributor and article edit log

### ISSUE THREAD

**Issue by BakerBelays** [observational-dev/oawiki#21]
Currently we don't account for who wrote, edited, added, or changed things in an article.

A log of who committed changes to an article and who wrote those changes should be available to readers- think a standard wiki history tab.

A full history akin to wikipedia or otherwise is likely unsustainable or difficult, but something simple like a log with a short description of each change and the author would be plenty. We won't have hundreds of edits from dozens of authors, we'll probably have *tens* of edits from 5 or 6. I think Fextralife's implementation is more than enough, as shown below. It's much more archaic than wikipedia's, but still shows who was active in the article.

![image](https://github.com/observational-dev/oawiki/assets/147800135/082dcfc2-dc8a-44db-9607-b619a1d17d61)

**Comment by random-person-001** [comment]
I fear that decoupling the contributors log from the article content will eventually make it easier to forget to update the contributor log than if contributors were recorded in the files they contributed to. That said, I'm not entirely opposed to this approach

**Comment by peytondmurray** [comment]
We can do this with git history, but we'll probably need to extend one of the templates to render the history into the article, and write a little python to handle fetching the history while sphinx is building. This should be totally possible. Maybe we can render this into a little tab or show/hide widget at the bottom of each article?

**Comment by peytondmurray** [comment]
I propose showing this in a modal dialog. @BakerBelays @finderskuipers what do you think? We can also hide it inside a different kind of widget if that makes more sense.
