### ISSUE TITLE
Populate article links

### ISSUE THREAD

**Issue by BakerBelays** [observational-dev/oawiki#39]
Links in articles need to be populated with pages. Currently, this is done manually. This will get quickly get laborious as number of articles and interlinking increases.

Ideally links could be automatically populated with articles either currently present in the repository or a stub article should be created for the repository.

Searching for a page, navigating to it, copy+paste the link, then paste link into github in the correct place, ad-infinitum is what I'm looking to avoid for writers. If there was a way to catalog pages and, say, select a link to have it pasted to clipboard automatically, it would remove half of the steps. You'd still need to link the page in the markdown source, but ideally a tool would exist to make this less painful.

The way wikipedia solves this problem is through a separate function than a link- a double bracket, say, [[newarticle]] and it either generates a stub or leads to the article in question. Wikipedia uses scant outward web-links, but perhaps this is a solution that could be applied in some way.

**Comment by peytondmurray** [comment]
The way we do this is by adding a `:glob:` directive to an article's `toctree`: https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-toctree. We'll still need to specify a `toctree` for each section, but this should take care of _groups_ of articles dumped into a directory.

**Comment by random-person-001** [comment]
For editors, it's easier come across a stub article and click the "edit on github" button and go from there. This is in contrast to going to the repo, forking, creating a file in the right directory, and updating other pages' links to it. Unless there are objections, I'll create a bunch of empty mds with the titles of what will come in there later.
