### ISSUE TITLE
Onboarding documentation

### ISSUE THREAD

**Issue by peytondmurray** [observational-dev/oawiki#4]
We need some documentation somewhere loud and clear on how to create issues and write content. This includes

- [x] Information for building the wiki locally (already done, it's in the `README.md`)
- [x] Creating github issues; probably we want to cover a few use cases here, including a content request issue ("I have an article but I don't have time to learn about github etc, how do I add stuff to the wiki"), bug reports, feature requests ("I want to write an article but I need some special features to make it really nice, please help"), and content modification requests ("there's a factual inaccuracy in this page, please correct it")

**Comment by random-person-001** [comment]
What are yall's thoughts on considering this closed/done for now?

**Comment by peytondmurray** [comment]
We can close this for now, but can there be a new issue about contribution that goes more in depth? Like the kind of content that is acceptable, discussion about proper attribution, etc might be useful for contributors.

**Comment by random-person-001** [comment]
Sounds good. #30 will be the place to go for the next step I think
