### ISSUE TITLE
Add Discord notifications

### ISSUE THREAD

**Issue by peytondmurray** [observational-dev/oawiki#6]
It would be nice to have a discord bot that reported new issues when they appear on the repo. @finderskuipers are you the right person to assign this to? Honestly I don't know how to do this but can probably figure it out given enough time. Please assign me or someone else if that would be better.

**Comment by random-person-001** [comment]
https://gist.github.com/jagrosh/5b1761213e33fc5b54ec7f6379034a22 shows a good guide to set up the webhook. I can work with Maff (as admin) to do so if I have perms for this repo, or one of you could equally well.

**Comment by random-person-001** [comment]
This is a test of the webhook.

**Comment by random-person-001** [comment]
Seems to be working now :+1:
