### ISSUE TITLE
Landing page with major links

### ISSUE THREAD

**Issue by peytondmurray** [observational-dev/oawiki#7]
We need a landing page with some major links. Here's inspiration:

![image](https://github.com/observational-dev/oawiki/assets/14017872/872f6afa-6323-4b83-804a-bd263f294183)

**Comment by BakerBelays** [comment]
Something simple to start, broad topics with opportunities for sub-pages

| Visual astronomy         | Astrophotography                    | Telescope making                 | For Beginners                                       |
|The Night Sky - Targets | Understanding AP - Wide Field | Newtonian Design - History | How to Observe - What should I buy   |
|Telescopes - Resources  | Planetary - Software                 | Materials - Resources           | How telescopes work - Observing Well |

**Comment by BakerBelays** [comment]
https://hackmd.io/@bakerbelays/SyJVd9_bT/edit

First splash page

**Comment by random-person-001** [comment]
Closed with 68ded15
